version: "3.9"

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    env_file:
      - ./user-service/.env

  dataset-service:
    build: ./dataset-service
    ports:
      - "3002:3002"
    env_file:
      - ./dataset-service/.env
    volumes:
      - ./shared-uploads:/app/shared-uploads
      - ./shared-reports:/app/shared-reports

  log-service:
    build: ./log-service
    ports:
      - "3004:3004"
    env_file:
      - ./log-service/.env

  prediction-service:
    build: ./prediction-service
    ports:
      - "3003:3003"
    env_file:
      - ./prediction-service/.env
    volumes:
      - ./shared-uploads:/app/shared-uploads
      - ./shared-results:/app/shared-results
      - ../thesisPython:/app/thesisPython